# -*- coding: utf-8 -*-
"""Data Cleaning - Ridwan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EBfy_DumfPPlvlpS3f4dM_GJQbLIkfvu

# Customer Behavior Analyzer
## Week 1: Data Cleaning & EDA
Dataset: Online Retail II (UCI)
Cleaning steps: remove nulls, cancelled orders, negative quantities/prices, duplicates
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

df1 = pd.read_excel("/content/online_retail_II.xlsx", sheet_name="Year 2009-2010")
df2 = pd.read_excel("/content/online_retail_II.xlsx", sheet_name="Year 2010-2011")

df = pd.concat([df1, df2], ignore_index=True)

#total null vals
df.isnull().sum()

# Rows where description is missing
missing_desc = df[df['Description'].isnull()]

# Check customer_id missing status within those rows
missing_desc['Customer ID'].isnull().value_counts()

#all that are missing description are missing customer ID as well!

#Data Cleaning Begin

#Basic info
print("Shape: ", df.shape)
print("\nColumns: ", df.columns)
print("\nData Types: ", df.dtypes)
print("\nMissing Values: ", df.isnull().sum())

print(df['Invoice'].astype(str).str.startswith('c').sum())

#cleaning continue
original_rows = df.shape[0]

df = df.dropna(subset=['Customer ID'])
df = df.dropna(subset=['Description'])
df = df[~df['Invoice'].astype(str).str.startswith('c')]
df = df[df['Quantity'] > 0]
df = df[df['Price'] > 0]
df = df.drop_duplicates()
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

cleaned_rows = df.shape[0]

# Check for negative values
print((df['Quantity'] < 0).sum())
print((df['Price'] < 0).sum())

# Summary stats
df[['Quantity', 'Price']].describe()

# Check nulls
df.isnull().sum()

#cleaned dataset info
print("\nCleaned shape: ", df.shape)
print(original_rows - cleaned_rows, ' rows removed')

#Data Cleaning End

#TOTAL PRICE CALCULATION (for use in EDA)
df['TotalPrice'] = df['Quantity'] * df['Price']
print(df[['Quantity', 'Price', 'TotalPrice']].head())
print((df['TotalPrice'] < 0).sum())

#first few printed